### ISSUE TITLE
Chosen does not update when ngOptions changes

### ISSUE THREAD

**Issue by dougludlow** [leocaseiro/angular-chosen#101]
When the object behind ngOptions updates, chosen doesn't appear to pick up the change. This situation becomes obvious when trying to create cascading dropdowns using the chosen directive as in this example: http://plnkr.co/edit/MiwbF8LWMYvuhpy7igrh?p=preview. 

You'll notice in the example that regular selects work as expected, but the selects using the chosen directive don't respond appropriately.

**Comment by b-heilman** [comment]
Yeah, the issue is that ng-options has a priority 0, as does chosen.  So chosen looks at the options in the select, which ng-options governs, sees nothing to do, and then ng-options kicks off.  It seems like the issue is chosen relies on DOM options and there isn't a way to have it sit back and wait without a $timeout...

**Comment by dougludlow** [comment]
The issue was that it wasn't updating chosen when ngOptions was empty. The
pull request I submitted fixes that.

**Comment by b-heilman** [comment]
I'm noticing the issue on more than just the empty case.

**Comment by dougludlow** [comment]
The directive doesn't override ngOptions functionality, it parses the ngOptions string to get the collection and adds a watch on the collection. When the collection changes and digest picks up the change jquery chosen is updated.

**Comment by b-heilman** [comment]
Well, yes, but Chosen's base code still runs off of the content that is in the DOM at the time of the update.  This means that if the chosen directive runs before ng-options, the DOM will not have been updated yet, thus the options for chosen will be one change behind the model they are both watching.  Both directive are priority 0, so they will run at the same time, but it seems it's usually Chosen first, then ng-options.  If your force another digest loop chosen will sync up correctly with the options, because it now has the correct DOM elements to parse and populate its list with.  That's what $timeout does.

The problem isn't so much the directive, but how it needs to interact with the underlying code as it is reliant on the state of the DOM and not the data model that's being passed in from angular's watch.  If ng-options was an priority of 1, chosen 0, we wouldn't have this issue, but both are 0, as that's the lowest you can go.

I have no problem with your PR, but the options not updating for Chosen is an issue that goes much deeper than your PR addresses.

**Comment by dougludlow** [comment]
Oh, I understand now. Thanks for clarifying.

**Comment by ukjbrown** [comment]
I'm not sure if this is the same issue I'm experiencing, but what is the solution? I have a list that is updated when the page loads, the <options> update in the list but chosen doesn't update.

**Comment by dougludlow** [comment]
The pr I linked to is the fix.
