### ISSUE TITLE
clarify relation to adityasharat/angular-chosen

### ISSUE THREAD

**Issue by madmas** [leocaseiro/angular-chosen#196]
Hi, 
I noticed that there is also [adityasharat/angular-chosen](https://github.com/adityasharat/angular-chosen). 
To make it easier for users to picker the library best for their use case, it would be helpful if you can add a section that  exaplains the relation or differences of the libraries to the README.

thanks a lot :)

**Comment by leocaseiro** [comment]
Hi @madmas,

I'm not interested in any competition. I believe in a free open web.

Be free to test both libraries and give your thoughts.

**Comment by madmas** [comment]
Hi @leocaseiro,
thanks for the fast reply :)
I like that approach, but also this information is useful when stumbling on the two libraries :)

**Comment by leocaseiro** [comment]
Hi @madmas,

I'm not sure what to say, I haven't tried the adityasharat's library.

We support bower and npm or cnd. I believe they are not in npm yet.
It works with `ng-if` or `ng-hide`. Can be **translated**. and the most diferential is to **add new item if no results match**. 

I'd say that [angular-chosen-localytics](https://github.com/leocaseiro/angular-chosen) works as good as any angular select + chosen. You can read more at the [documentation website](http://leocaseiro.github.io/angular-chosen/).

If your code works with `<select>`, it should work with this directive as well. Otherwise, please open an Issue.

We are compatible with a "create new item", like you can read in more details at the documentation.
(http://leocaseiro.github.io/angular-chosen/#create-new-item-on-no-resuls-match)

> Angular Chosen, didn’t accept one if they [most wanted feature](https://github.com/harvesthq/chosen/pull/166) which is **add new item if no results match**. However, there’s a fork that adds this feature and Angular Chosen is compatible with.

**Comment by madmas** [comment]
Hi @leocaseiro ,
thanks a lot for the reply and explanation/overview, that helps :-) 
What do you think about to include it as a section to the readme that contains the summary and a list "other known implementations" or something?

**Comment by leocaseiro** [comment]
Hi @madmas, would you like to send a Pull Request?
