### ISSUE TITLE
Issue with resetting all selections

### ISSUE THREAD

**Issue by bgadiel** [leocaseiro/angular-chosen#243]
Hi Leo,
I used to reset all user selection by updating the model to an empty array.
I suspect that this no longer works with newer versions.

Any ideas on what is the recommended way to reset selections?

https://plnkr.co/edit/80Et38V3CpE2i1LNfp2m?p=preview

Angular-chosen 1.7.0
AngularJS 1.6.2

Thanks.

**Comment by leocaseiro** [comment]
Hi @bgadiel, thanks for reporting that.

I confirmed this is a bug.
I've tried some techniques, but I'll probably need to investigate what is the issue.

Please, use @angular-cholse@1.4.2 for the time being.

I'll check what went wrong since [1.4.3](https://github.com/leocaseiro/angular-chosen/tree/1.4.3)
