### ISSUE TITLE
filtering with chosen control

### ISSUE THREAD

**Issue by chetanra** [leocaseiro/angular-chosen#63]
jsfiddle with filter: http://jsfiddle.net/wKMZM/11/

Any idea why the filtering is not kicking in? I was expecting to see ninja cat selected in the controller similar to http://jsfiddle.net/wKMZM/10/.

Posted on SO also at: http://stackoverflow.com/questions/24909938/angularjs-filtering-with-chosen-control

**Comment by leocaseiro** [comment]
Hi @chetanra, first of all, I'm really sorry for delay, I'm the new maintainer of this project (Read more #162) and I'd like to fix your issue.

I was wondering if you already came with any solution.

I normally adopt the pattern you used here http://jsfiddle.net/wKMZM/10/

Otherwise, I'd do some kind of watch, like:

```javascript
$scope.lol = {
    cats: [
      'longcat',
      'ninjacat',
      'monorail cat'
    ]
  };

  $scope.fullModel = [{
    type: 'ninjacat'
  }];

  $scope.$watch('fullModel', function(myModels) {
    $scope.myModel = [];
    angular.forEach(myModels, function(myModel) {
      $scope.myModel.push(myModel.type);
    });
  });  
```

Would that fix your issue?

PS: you can try with a normal `<select>` first. It should work in both way
