### ISSUE TITLE
ng-model bug: Options shifted by one after selecting the first time

### ISSUE THREAD

**Issue by martin-wintz** [leocaseiro/angular-chosen#8]
If you use the ng-model attribute, all the `data-option-array-index` attributes for li the elements under the `chosen-results` list are shifted by one (1, 2, 3... instead of 0, 1, 2...). Selection works the first time -- I'm guessing because the placeholder option is in the array and shifting all the other elements -- but every subsequent selection actually assigns the value after the selected value to the model (click on the second option, and the model is assigned the value for the third option). Picking the last value causes JQuery to throw an error.

How to reproduce:
Open `angular-chosen/example/index.html`
Pick a value from "Chosen with static options"
Pick another one and watch the model update to the value after it (or if the value selected is the last one, see JQuery throw an error in the console)

I'll try to see if I can fix it.

**Comment by hylegoz** [comment]
I think that this issue is covered in the recent documentation. Just add an empty valued option element:

>https://github.com/localytics/angular-chosen

>Also important: if your ngModel is null or undefined, you must manually include an empty option inside your <select>, otherwise you'll encounter strange off-by-one errors.

**Comment by jchurchley** [comment]
Used  <option value="" ng-if="false"></option> to get around this issue

**Comment by sebferrer** [comment]
I just had the same problem lately, but I wasn't able to use the ng-init solution because my options were generated by ajax, so when the ng-init was applied, my array wasn't filled yet.

I used a very simple solution, I'm not sure if it's the best (I'm a beginner with Angular), but it worked very well for me. I just deleted the first empty option generated by Chosen, just before activate Chosen for my select : $('#mySelect option').eq(0).remove();

**Comment by SvistunovYuriy** [comment]
Also, you can call $('#yourSelect').trigger('chosen:updated'), but it is not angular way
